#!/usr/bin/python3

import time

from tile_player import TilePlayer


if __name__ == "__main__":
    tile_player = TilePlayer()
    thread = tile_player.start(run_in_thread=True)

    time.sleep(5)
    tile_player.select_output(1)
    time.sleep(5)
    tile_player.select_output(2)
    time.sleep(5)
    tile_player.select_output(0)
    thread.join()
